% rotation_matrices
% generate rotation matrices for a given 3D angle
function [RX, RY, RZ] = rotation_matrices(angle)

    RX = [ [1,             0,              0];...
       [0, cos(angle(1)), -sin(angle(1))];...
       [0, sin(angle(1)),  cos(angle(1))]];
   
    RY = [ [cos(angle(2)), 0, sin(angle(2))];...
       [0            , 1,             0];...
       [-sin(angle(2))  , 0,   cos(angle(2))]];
   
    RZ = [ [cos(angle(3)), -sin(angle(3)), 0];...
       [sin(angle(3)),  cos(angle(3)), 0];...
       [            0,              0, 1]];
end
